language: node_js

node_js:
  - "12"

# prevent infinite looping build
branches:
  except:
    - master
    - 2020-redesign

before_install:
  - npm i -g npm@4.2.0

install:
  - npm install
  - npm run build

before_deploy:
  - rm .gitignore
  - rm src -r
  - rm node_modules -rf
  - rm package.json
  - rm yarn.lock
  - rm webpack.data.js
  - rm data.js
  - rm log.txt

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN 
  keep-history: true
  target-branch: master
  on:
    branch: develop
