language: node_js
node_js:
  - "7"
before_install:
  - npm i -g npm@4.2.0
install:
  - npm install
  - npm run build
  - rm .gitignore
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN 
  keep-history: true
  target-branch: master
  on:
    branch: develop
