language: node_js

node_js:
  - "7"

# prevent infinite looping build
branches:
  except:
    - master

before_install:
  - npm i -g npm@4.2.0

install:
  - npm install
  - npm run build

before_deploy:
  - rm .gitignore
  - rm src -r
  - rm node_modules -r
  - rm package.json
  - rm webpack.config.js

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN 
  keep-history: true
  target-branch: master
  on:
    branch: develop
